function aggregate = aggregateRecoveryMetrics(realizations)
%AGGREGATERECOVERYMETRICS Summarize metric sequences across realizations.

assert(iscell(realizations) && ~isempty(realizations), ...
    'dynsc:MissingRealizations', ...
    'realizations must be a nonempty cell array.');

nRealizations = numel(realizations);
hasPrimary = cellfun(@(r) isfield(r, 'metrics') && ...
    ~isempty(r.metrics), realizations);
assert(all(hasPrimary), 'dynsc:MissingPrimaryMetrics', ...
    'Every realization must contain primary-filter metrics.');

hasIdentity = cellfun(@(r) isfield(r, 'identityBaseline') && ...
    ~isempty(r.identityBaseline) && ...
    isfield(r.identityBaseline, 'metrics') && ...
    ~isempty(r.identityBaseline.metrics), realizations);
hasConstrainedRls = cellfun(@(r) ...
    isfield(r, 'constrainedRlsBaseline') && ...
    ~isempty(r.constrainedRlsBaseline) && ...
    isfield(r.constrainedRlsBaseline, 'metrics') && ...
    ~isempty(r.constrainedRlsBaseline.metrics), realizations);
hasStatic = cellfun(@(r) isfield(r, 'staticBaseline') && ...
    ~isempty(r.staticBaseline) && ...
    isfield(r.staticBaseline, 'metrics') && ...
    ~isempty(r.staticBaseline.metrics), realizations);
hasPreviousUpdate = cellfun(@(r) ...
    isfield(r, 'previousUpdateBaseline') && ...
    ~isempty(r.previousUpdateBaseline) && ...
    isfield(r.previousUpdateBaseline, 'metrics') && ...
    ~isempty(r.previousUpdateBaseline.metrics), realizations);
hasExactHessian = cellfun(@(r) ...
    isfield(r, 'exactHessianBaseline') && ...
    ~isempty(r.exactHessianBaseline) && ...
    isfield(r.exactHessianBaseline, 'metrics') && ...
    ~isempty(r.exactHessianBaseline.metrics), realizations);
hasStandardEkf = cellfun(@(r) ...
    isfield(r, 'standardEkfBarrierBaseline') && ...
    ~isempty(r.standardEkfBarrierBaseline) && ...
    isfield(r.standardEkfBarrierBaseline, 'metrics') && ...
    ~isempty(r.standardEkfBarrierBaseline.metrics), realizations);

assert(all(hasIdentity) || ~any(hasIdentity), ...
    'dynsc:InconsistentIdentityMetrics', ...
    ['The persistence-prior baseline must be present in either every ' ...
     'realization or none of them.']);
assert(all(hasConstrainedRls) || ~any(hasConstrainedRls), ...
    'dynsc:InconsistentConstrainedRlsMetrics', ...
    ['The constrained-RLS baseline must be present in either every ' ...
     'realization or none of them.']);
assert(all(hasStatic) || ~any(hasStatic), ...
    'dynsc:InconsistentStaticMetrics', ...
    ['The static baseline must be present in either every realization ' ...
     'or none of them.']);
assert(all(hasPreviousUpdate) || ~any(hasPreviousUpdate), ...
    'dynsc:InconsistentPreviousUpdateMetrics', ...
    ['The previous-update baseline must be present in either every ' ...
     'realization or none of them.']);
assert(all(hasExactHessian) || ~any(hasExactHessian), ...
    'dynsc:InconsistentExactHessianMetrics', ...
    ['The exact-Hessian baseline must be present in either every ' ...
     'realization or none of them.']);
assert(all(hasStandardEkf) || ~any(hasStandardEkf), ...
    'dynsc:InconsistentStandardEkfMetrics', ...
    ['The standard-EKF barrier baseline must be present in either every ' ...
     'realization or none of them.']);

primaryMetrics = cellfun(@(r) r.metrics, realizations, ...
    'UniformOutput', false);
reference = primaryMetrics{1};
validateCommonMetricConfiguration(primaryMetrics, reference);

aggregate = struct();
aggregate.numRealizations = nRealizations;
aggregate.time = reference.time;
aggregate.supportThreshold = reference.supportThreshold;
aggregate.methodOrder = [ ...
    "Static", "Persistence", "Constrained RLS", "Constrained MAP", ...
    "EKF", "IEKF", "Laplace"];
aggregate.iekf = summarizeEstimator(primaryMetrics, "IEKF");
% Retain legacy aliases so existing analysis scripts continue to work.
aggregate.primary = aggregate.iekf;

if all(hasStandardEkf)
    standardEkfMetrics = cellfun( ...
        @(r) r.standardEkfBarrierBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(standardEkfMetrics, reference);
    aggregate.ekf = summarizeEstimator(standardEkfMetrics, "EKF");
    aggregate.standardEkfBarrier = aggregate.ekf;
else
    aggregate.ekf = [];
    aggregate.standardEkfBarrier = [];
end

if all(hasExactHessian)
    exactHessianMetrics = cellfun( ...
        @(r) r.exactHessianBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(exactHessianMetrics, reference);
    aggregate.laplace = summarizeEstimator(exactHessianMetrics, "Laplace");
    aggregate.exactHessian = aggregate.laplace;
else
    aggregate.laplace = [];
    aggregate.exactHessian = [];
end

if all(hasPreviousUpdate)
    previousUpdateMetrics = cellfun( ...
        @(r) r.previousUpdateBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(previousUpdateMetrics, reference);
    aggregate.constrainedMap = summarizeEstimator( ...
        previousUpdateMetrics, "Constrained MAP");
    aggregate.previousUpdate = aggregate.constrainedMap;
else
    aggregate.constrainedMap = [];
    aggregate.previousUpdate = [];
end

if all(hasIdentity)
    identityMetrics = cellfun( ...
        @(r) r.identityBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(identityMetrics, reference);
    aggregate.persistence = summarizeEstimator( ...
        identityMetrics, "Persistence");
    aggregate.identity = aggregate.persistence;
else
    aggregate.persistence = [];
    aggregate.identity = [];
end

if all(hasConstrainedRls)
    constrainedRlsMetrics = cellfun( ...
        @(r) r.constrainedRlsBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(constrainedRlsMetrics, reference);
    aggregate.constrainedRls = summarizeEstimator( ...
        constrainedRlsMetrics, "Constrained RLS");
else
    aggregate.constrainedRls = [];
end

if all(hasStatic)
    staticMetrics = cellfun( ...
        @(r) r.staticBaseline.metrics, realizations, ...
        'UniformOutput', false);
    validateCommonMetricConfiguration(staticMetrics, reference);
    aggregate.static = summarizeEstimator(staticMetrics, "Static");
else
    aggregate.static = [];
end

topologyChanged = zeros(nRealizations, numel(reference.time));
for iRealization = 1:nRealizations
    topologyChanged(iRealization, :) = ...
        double(primaryMetrics{iRealization}.topologyChanged);
end
aggregate.topologyChangeFraction = summarizeSeries(topologyChanged);
end

function validateCommonMetricConfiguration(metricSet, reference)
nTime = numel(reference.time);
for iMetric = 1:numel(metricSet)
    metrics = metricSet{iMetric};
    assert(isequal(metrics.time, reference.time), ...
        'dynsc:AggregateTimeMismatch', ...
        'All realizations and estimators must use the same time indices.');
    assert(isequal(metrics.supportThreshold, reference.supportThreshold), ...
        'dynsc:AggregateThresholdMismatch', ...
        'All realizations must use the same support threshold.');
    assert(numel(metrics.edge.supportF1) == nTime && ...
        numel(metrics.triangle.supportF1) == nTime && ...
        numel(metrics.edge.relativeError) == nTime && ...
        numel(metrics.triangle.relativeError) == nTime, ...
        'dynsc:AggregateMetricSizeMismatch', ...
        'Every metric sequence must match the common time vector.');
    hasEdgeSHD = isfield(metrics.edge, 'normalizedSHD');
    hasTriangleSHD = isfield(metrics.triangle, 'normalizedSHD');
    assert(hasEdgeSHD == hasTriangleSHD, ...
        'dynsc:IncompleteNormalizedSHD', ...
        ['Normalized SHD must be available for both simplex levels or ' ...
         'neither level.']);
    if hasEdgeSHD
        assert(numel(metrics.edge.normalizedSHD) == nTime && ...
            numel(metrics.triangle.normalizedSHD) == nTime, ...
            'dynsc:AggregateMetricSizeMismatch', ...
            ['Every normalized-SHD sequence must match the common ' ...
             'time vector.']);
    end
end
end

function summary = summarizeEstimator(metricSet, name)
nRealizations = numel(metricSet);
nTime = numel(metricSet{1}.time);

edgeF1 = zeros(nRealizations, nTime);
triangleF1 = zeros(nRealizations, nTime);
edgeError = zeros(nRealizations, nTime);
triangleError = zeros(nRealizations, nTime);
hasNormalizedSHD = ...
    isfield(metricSet{1}.edge, 'normalizedSHD') && ...
    isfield(metricSet{1}.triangle, 'normalizedSHD');
if hasNormalizedSHD
    edgeNormalizedSHD = zeros(nRealizations, nTime);
    triangleNormalizedSHD = zeros(nRealizations, nTime);
else
    edgeNormalizedSHD = zeros(nRealizations, 0);
    triangleNormalizedSHD = zeros(nRealizations, 0);
end
hasPriorResidual = ~isempty(metricSet{1}.priorResidualNorm);
if hasPriorResidual
    priorResidual = zeros(nRealizations, nTime);
else
    priorResidual = zeros(nRealizations, 0);
end

for iRealization = 1:nRealizations
    metrics = metricSet{iRealization};
    edgeF1(iRealization, :) = metrics.edge.supportF1;
    triangleF1(iRealization, :) = metrics.triangle.supportF1;
    edgeError(iRealization, :) = metrics.edge.relativeError;
    triangleError(iRealization, :) = metrics.triangle.relativeError;
    currentHasNormalizedSHD = ...
        isfield(metrics.edge, 'normalizedSHD') && ...
        isfield(metrics.triangle, 'normalizedSHD');
    assert(currentHasNormalizedSHD == hasNormalizedSHD, ...
        'dynsc:InconsistentNormalizedSHD', ...
        ['Normalized SHD must be present in either every realization ' ...
         'or none of them.']);
    if hasNormalizedSHD
        edgeNormalizedSHD(iRealization, :) = ...
            metrics.edge.normalizedSHD;
        triangleNormalizedSHD(iRealization, :) = ...
            metrics.triangle.normalizedSHD;
    end
    assert(isempty(metrics.priorResidualNorm) == ~hasPriorResidual, ...
        'dynsc:AggregatePriorResidualMismatch', ...
        ['Prior-residual sequences must be present in either every ' ...
         'realization or none of them.']);
    if hasPriorResidual
        assert(numel(metrics.priorResidualNorm) == nTime, ...
            'dynsc:AggregatePriorResidualSizeMismatch', ...
            'Each prior-residual sequence must match the common time vector.');
        priorResidual(iRealization, :) = metrics.priorResidualNorm;
    end
end

summary = struct();
summary.name = string(name);
if hasPriorResidual
    summary.priorResidualNorm = summarizeSeries(priorResidual);
else
    summary.priorResidualNorm = [];
end
summary.edge.supportF1 = summarizeSeries(edgeF1);
summary.edge.relativeError = summarizeSeries(edgeError);
summary.triangle.supportF1 = summarizeSeries(triangleF1);
summary.triangle.relativeError = summarizeSeries(triangleError);
if hasNormalizedSHD
    summary.edge.normalizedSHD = summarizeSeries(edgeNormalizedSHD);
    summary.triangle.normalizedSHD = ...
        summarizeSeries(triangleNormalizedSHD);
else
    summary.edge.normalizedSHD = [];
    summary.triangle.normalizedSHD = [];
end
end

function summary = summarizeSeries(values)
finiteValues = values;
finiteValues(~isfinite(finiteValues)) = NaN;

summary = struct();
summary.values = values;
summary.mean = mean(finiteValues, 1, 'omitnan');
summary.std = std(finiteValues, 0, 1, 'omitnan');
summary.numFinite = sum(isfinite(values), 1);
end
