function [figures, snapshotIndices] = plotUpdatedStateSnapshots( ...
    filterResult, topology, visible, snapshotInterval, baselineResult, ...
    identityResult, previousUpdateResult, exactHessianResult, ...
    standardEkfResult, constrainedRlsResult)
%PLOTUPDATEDSTATESNAPSHOTS Plot selected dynamic-state estimates separately.
%
% One figure is created at k=1, every snapshotInterval iterations, and the
% final iteration. Each figure compares the relaxed estimate with the binary
% ground-truth support active at that same time.

if nargin < 3
    visible = true;
end
if nargin < 4
    snapshotInterval = 5;
end
if nargin < 5
    baselineResult = [];
end
if nargin < 6
    identityResult = [];
end
if nargin < 7
    previousUpdateResult = [];
end
if nargin < 8
    exactHessianResult = [];
end
if nargin < 9
    standardEkfResult = [];
end
if nargin < 10
    constrainedRlsResult = [];
end

validateattributes(snapshotInterval, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});

if visible
    visibility = 'on';
else
    visibility = 'off';
end

updatedState = filterResult.updatedState;
if isempty(baselineResult)
    baselineState = [];
else
    assert(isfield(baselineResult, 'estimatedState'), ...
        'dynsc:MissingBaselineState', ...
        'The static baseline result must contain estimatedState.');
    baselineState = baselineResult.estimatedState;
end
if isempty(identityResult)
    identityState = [];
else
    assert(isfield(identityResult, 'updatedState'), ...
        'dynsc:MissingIdentityBaselineState', ...
        'The persistence-prior baseline must contain updatedState.');
    identityState = identityResult.updatedState;
end
if isempty(constrainedRlsResult)
    constrainedRlsState = [];
else
    assert(isfield(constrainedRlsResult, 'updatedState'), ...
        'dynsc:MissingConstrainedRlsBaselineState', ...
        'The constrained-RLS baseline must contain updatedState.');
    constrainedRlsState = constrainedRlsResult.updatedState;
end
if isempty(previousUpdateResult)
    previousUpdateState = [];
else
    assert(isfield(previousUpdateResult, 'updatedState'), ...
        'dynsc:MissingPreviousUpdateBaselineState', ...
        'The previous-update baseline must contain updatedState.');
    previousUpdateState = previousUpdateResult.updatedState;
end
if isempty(exactHessianResult)
    exactHessianState = [];
else
    assert(isfield(exactHessianResult, 'updatedState'), ...
        'dynsc:MissingExactHessianBaselineState', ...
        'The exact-Hessian baseline must contain updatedState.');
    exactHessianState = exactHessianResult.updatedState;
end
if isempty(standardEkfResult)
    standardEkfState = [];
else
    assert(isfield(standardEkfResult, 'updatedState'), ...
        'dynsc:MissingStandardEkfBaselineState', ...
        'The standard-EKF barrier baseline must contain updatedState.');
    standardEkfState = standardEkfResult.updatedState;
end
nTime = size(updatedState, 2);
nEdges = size(topology.B1_full, 2);
nTriangles = size(topology.B2_full, 2);

assert(size(updatedState, 1) == nEdges + nTriangles, ...
    'dynsc:PlotStateSizeMismatch', ...
    'The updated state does not match the topology dimensions.');
if ~isempty(baselineState)
    assert(isequal(size(baselineState), size(updatedState)), ...
        'dynsc:PlotBaselineSizeMismatch', ...
        ['The static and dynamic estimated-state sequences must have ' ...
         'matching dimensions.']);
end
if ~isempty(identityState)
    assert(isequal(size(identityState), size(updatedState)), ...
        'dynsc:PlotIdentityBaselineSizeMismatch', ...
        ['The persistence-prior and primary estimated-state sequences ' ...
         'must have matching dimensions.']);
end
if ~isempty(constrainedRlsState)
    assert(isequal(size(constrainedRlsState), size(updatedState)), ...
        'dynsc:PlotConstrainedRlsBaselineSizeMismatch', ...
        ['The constrained-RLS and primary estimated-state sequences ' ...
         'must have matching dimensions.']);
end
if ~isempty(previousUpdateState)
    assert(isequal(size(previousUpdateState), size(updatedState)), ...
        'dynsc:PlotPreviousUpdateBaselineSizeMismatch', ...
        ['The previous-update and primary estimated-state sequences ' ...
         'must have matching dimensions.']);
end
if ~isempty(exactHessianState)
    assert(isequal(size(exactHessianState), size(updatedState)), ...
        'dynsc:PlotExactHessianBaselineSizeMismatch', ...
        ['The exact-Hessian and primary estimated-state sequences ' ...
         'must have matching dimensions.']);
end
if ~isempty(standardEkfState)
    assert(isequal(size(standardEkfState), size(updatedState)), ...
        'dynsc:PlotStandardEkfBaselineSizeMismatch', ...
        ['The standard-EKF barrier and primary state sequences must ' ...
         'have matching dimensions.']);
end
assert(size(topology.s1, 1) == nEdges && ...
    size(topology.s2, 1) == nTriangles && ...
    size(topology.s1, 2) == nTime && ...
    size(topology.s2, 2) == nTime, ...
    'dynsc:PlotTopologySizeMismatch', ...
    ['The ground-truth edge and triangle sequences must match the ' ...
     'estimated state sequence.']);

snapshotIndices = unique( ...
    [1, snapshotInterval:snapshotInterval:nTime, nTime], 'stable');
figures = gobjects(1, numel(snapshotIndices));

edgeColor = [0.1216, 0.4667, 0.7059];
triangleColor = [1.0000, 0.4980, 0.0549];
baselineEdgeColor = [0.30, 0.30, 0.30];
baselineTriangleColor = [0.60, 0.60, 0.60];
identityEdgeColor = [0.4940, 0.1840, 0.5560];
identityTriangleColor = [0.4660, 0.6740, 0.1880];
constrainedRlsEdgeColor = [0.1500, 0.1500, 0.1500];
constrainedRlsTriangleColor = [0.8500, 0.4500, 0.1000];
previousUpdateColor = [0.6350, 0.0780, 0.1840];
exactHessianColor = [0.0000, 0.6000, 0.6000];
standardEkfColor = [0.5490, 0.3373, 0.2941];
triangleRows = nEdges + (1:nTriangles);
identityDisplayName = resultName(identityResult, "Persistence");
constrainedRlsDisplayName = resultName( ...
    constrainedRlsResult, "Constrained RLS");

for iSnapshot = 1:numel(snapshotIndices)
    iTime = snapshotIndices(iSnapshot);
    figures(iSnapshot) = figure( ...
        'Color', 'w', 'Visible', visibility, ...
        'Position', [100, 100, 1200, 650]);
    layout = tiledlayout(figures(iSnapshot), 2, 1, ...
        'TileSpacing', 'compact', 'Padding', 'compact');

    edgeAxis = nexttile(layout);
    plotStateBlock(edgeAxis, updatedState(1:nEdges, iTime), ...
        selectBaselineBlock(baselineState, 1:nEdges, iTime), ...
        selectBaselineBlock(identityState, 1:nEdges, iTime), ...
        selectBaselineBlock(constrainedRlsState, 1:nEdges, iTime), ...
        selectBaselineBlock(previousUpdateState, 1:nEdges, iTime), ...
        selectBaselineBlock(exactHessianState, 1:nEdges, iTime), ...
        selectBaselineBlock(standardEkfState, 1:nEdges, iTime), ...
        topology.s1(:, iTime), edgeColor, '-', 'd', ...
        baselineEdgeColor, ':', 'o', ...
        identityEdgeColor, '--', 'x', identityDisplayName, ...
        constrainedRlsEdgeColor, ':', '+', ...
        constrainedRlsDisplayName, ...
        previousUpdateColor, '-.', 'p', ...
        exactHessianColor, '-', 'h', ...
        standardEkfColor, '--', 's', ...
        'Candidate edge index', 'Updated edge weight', ...
        'Edge state', nEdges);

    triangleAxis = nexttile(layout);
    plotStateBlock(triangleAxis, ...
        updatedState(triangleRows, iTime), ...
        selectBaselineBlock(baselineState, triangleRows, iTime), ...
        selectBaselineBlock(identityState, triangleRows, iTime), ...
        selectBaselineBlock(constrainedRlsState, triangleRows, iTime), ...
        selectBaselineBlock(previousUpdateState, triangleRows, iTime), ...
        selectBaselineBlock(exactHessianState, triangleRows, iTime), ...
        selectBaselineBlock(standardEkfState, triangleRows, iTime), ...
        topology.s2(:, iTime), triangleColor, '--', 's', ...
        baselineTriangleColor, '-.', '^', ...
        identityTriangleColor, ':', '+', identityDisplayName, ...
        constrainedRlsTriangleColor, '-.', 'x', ...
        constrainedRlsDisplayName, ...
        previousUpdateColor, '-', 'p', ...
        exactHessianColor, '--', 'h', ...
        standardEkfColor, ':', 's', ...
        'Candidate triangle index', 'Updated triangle weight', ...
        'Triangle state', nTriangles);

    title(layout, sprintf( ...
        'Updated state and ground-truth support at k = %d', iTime));
end
end

function block = selectBaselineBlock(baselineState, rows, iTime)
if isempty(baselineState)
    block = [];
else
    block = baselineState(rows, iTime);
end
end


function name = resultName(result, fallback)
name = fallback;
if ~isempty(result) && isfield(result, 'name') && ...
        strlength(string(result.name)) > 0
    name = string(result.name);
end
end

function plotStateBlock( ...
    axisHandle, estimate, baselineEstimate, identityEstimate, ...
    constrainedRlsEstimate, previousUpdateEstimate, ...
    exactHessianEstimate, standardEkfEstimate, ...
    truth, ...
    color, lineStyle, marker, baselineColor, baselineLineStyle, ...
    baselineMarker, identityColor, identityLineStyle, identityMarker, ...
    identityDisplayName, ...
    constrainedRlsColor, constrainedRlsLineStyle, ...
    constrainedRlsMarker, constrainedRlsDisplayName, ...
    previousUpdateColor, previousUpdateLineStyle, previousUpdateMarker, ...
    exactHessianColor, exactHessianLineStyle, exactHessianMarker, ...
    standardEkfColor, standardEkfLineStyle, standardEkfMarker, ...
    xLabel, yLabel, axisTitle, nEntries)
hold(axisHandle, 'on');

if ~isempty(baselineEstimate)
    stem(axisHandle, 1:nEntries, baselineEstimate, ...
        'Color', baselineColor, ...
        'LineStyle', baselineLineStyle, ...
        'LineWidth', 1.3, ...
        'Marker', baselineMarker, ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', 'Static');
end

if ~isempty(identityEstimate)
    stem(axisHandle, 1:nEntries, identityEstimate, ...
        'Color', identityColor, ...
        'LineStyle', identityLineStyle, ...
        'LineWidth', 1.5, ...
        'Marker', identityMarker, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', identityDisplayName);
end

if ~isempty(constrainedRlsEstimate)
    stem(axisHandle, 1:nEntries, constrainedRlsEstimate, ...
        'Color', constrainedRlsColor, ...
        'LineStyle', constrainedRlsLineStyle, ...
        'LineWidth', 1.5, ...
        'Marker', constrainedRlsMarker, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', constrainedRlsDisplayName);
end

if ~isempty(previousUpdateEstimate)
    stem(axisHandle, 1:nEntries, previousUpdateEstimate, ...
        'Color', previousUpdateColor, ...
        'LineStyle', previousUpdateLineStyle, ...
        'LineWidth', 1.5, ...
        'Marker', previousUpdateMarker, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', 'Constrained MAP');
end

if ~isempty(standardEkfEstimate)
    stem(axisHandle, 1:nEntries, standardEkfEstimate, ...
        'Color', standardEkfColor, ...
        'LineStyle', standardEkfLineStyle, ...
        'LineWidth', 1.6, ...
        'Marker', standardEkfMarker, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', 'EKF');
end

stem(axisHandle, 1:nEntries, estimate, ...
    'Color', color, ...
    'LineStyle', lineStyle, ...
    'LineWidth', 1.8, ...
    'Marker', marker, ...
    'MarkerSize', 7, ...
    'MarkerFaceColor', 'none', ...
    'ShowBaseLine', 'off', ...
    'DisplayName', 'IEKF');

if ~isempty(exactHessianEstimate)
    stem(axisHandle, 1:nEntries, exactHessianEstimate, ...
        'Color', exactHessianColor, ...
        'LineStyle', exactHessianLineStyle, ...
        'LineWidth', 1.6, ...
        'Marker', exactHessianMarker, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', 'none', ...
        'ShowBaseLine', 'off', ...
        'DisplayName', 'Laplace');
end

trueSupport = find(truth > 0);
if isempty(trueSupport)
    supportX = nan;
    supportY = nan;
else
    supportX = trueSupport;
    supportY = ones(size(trueSupport));
end
plot(axisHandle, supportX, supportY, ...
    'ko', 'LineStyle', 'none', 'MarkerFaceColor', 'none', ...
    'MarkerSize', 10, 'LineWidth', 1.6, ...
    'DisplayName', 'Ground-truth support');

xlabel(axisHandle, xLabel);
ylabel(axisHandle, yLabel);
title(axisHandle, axisTitle);
xlim(axisHandle, [0.5, max(2, nEntries + 0.5)]);
ylim(axisHandle, [0, 1.08]);
grid(axisHandle, 'on');
box(axisHandle, 'on');
axisHandle.FontSize = 12;
legend(axisHandle, 'Location', 'northeastoutside');
end
