function update = solveConfiguredUpdate( ...
    predictedState, predictedCovariance, y, H, noiseCovariance, ...
    topology, updateConfig, gurobiParameters)
%SOLVECONFIGUREDUPDATE Dispatch to the selected correction model.

if nargin < 8
    gurobiParameters = [];
end
method = "constrained_map";
if nargin >= 7 && ~isempty(updateConfig) && isfield(updateConfig, 'method')
    method = string(updateConfig.method);
end

switch method
    case "constrained_map"
        update = dynsc.update.solveConstrainedUpdateGurobi( ...
            predictedState, predictedCovariance, y, H, ...
            noiseCovariance, topology, gurobiParameters);
        update.method = method;
        update.solverName = "Gurobi";
        update.solverStatus = string(update.gurobiResult.status);

    case "barrier_virtual_measurement"
        assert(isfield(updateConfig, 'barrier'), ...
            'dynsc:MissingBarrierUpdateConfig', ...
            ['The barrier_virtual_measurement update requires ' ...
             'cfg.update.barrier.']);
        barrierConfig = updateConfig.barrier;
        barrierConfig.covarianceMode = "gauss_newton";
        barrierConfig.updateMethod = method;
        update = dynsc.update.solveBarrierVirtualMeasurementUpdate( ...
            predictedState, predictedCovariance, y, H, ...
            noiseCovariance, topology, barrierConfig);

    case "barrier_exact_hessian"
        assert(isfield(updateConfig, 'barrier'), ...
            'dynsc:MissingBarrierUpdateConfig', ...
            ['The barrier_exact_hessian update requires ' ...
             'cfg.update.barrier.']);
        barrierConfig = updateConfig.barrier;
        barrierConfig.covarianceMode = "exact_hessian";
        barrierConfig.updateMethod = method;
        update = dynsc.update.solveBarrierVirtualMeasurementUpdate( ...
            predictedState, predictedCovariance, y, H, ...
            noiseCovariance, topology, barrierConfig);

    case "barrier_standard_ekf_projection"
        assert(isfield(updateConfig, 'barrier'), ...
            'dynsc:MissingBarrierUpdateConfig', ...
            ['The barrier_standard_ekf_projection update requires ' ...
             'cfg.update.barrier.']);
        update = dynsc.update.solveStandardEkfBarrierProjection( ...
            predictedState, predictedCovariance, y, H, ...
            noiseCovariance, topology, updateConfig.barrier, ...
            gurobiParameters);

    otherwise
        error('dynsc:UnknownUpdateMethod', ...
            'Unknown correction method: %s.', method);
end
end
