function update = solveBarrierVirtualMeasurementUpdate( ...
    predictedState, predictedCovariance, y, H, noiseCovariance, ...
    topology, barrierConfig)
%SOLVEBARRIERVIRTUALMEASUREMENTUPDATE Fixed log-barrier MAP correction.
%
% The corrected mean minimizes the Gaussian negative log posterior plus
% scalar inclusion and box log barriers:
%
%   1/2 ||s-sPred||^2_PPred^{-1}
% + 1/2 ||y-Hs||^2_R^{-1}
% + lambda_inc [-sum log(A_inc*s)]
% + lambda_box [-sum(log(s)+log(1-s))].
%
% covarianceMode selects the local curvature used at the final MAP state:
% "gauss_newton" uses the final-estimate Jacobians of
%
%   h_inc(s) = sqrt(-sum log(A_inc*s)),
%   h_box(s) = sqrt(-sum(log(s)+log(1-s))).
%
% Since lambda = 1/(2*sigma^2), each scalar measurement contributes
% 2*lambda*j*j' to the posterior information matrix. "exact_hessian"
% instead adds the exact Hessians of the two weighted log-barrier terms.
% The corrected mean and its objective are identical in both modes.

predictedState = predictedState(:);
y = y(:);
nState = numel(predictedState);
nMeasurements = numel(y);
nEdges = size(topology.B1_full, 2);
nTriangles = size(topology.B2_full, 2);

assert(nState == nEdges + nTriangles, ...
    'dynsc:UpdateStateSizeMismatch', ...
    'The state must contain %d edge and %d triangle entries.', ...
    nEdges, nTriangles);
assert(isfield(topology, 'boundaryEdges'), ...
    'dynsc:MissingBoundaryEdges', ...
    ['The barrier update requires the shared topology.boundaryEdges ' ...
     'index matrix.']);
validateattributes(predictedState, {'numeric'}, ...
    {'column', 'real', 'finite'});
validateattributes(predictedCovariance, {'numeric'}, ...
    {'real', 'finite', 'size', [nState, nState]});
validateattributes(H, {'numeric'}, ...
    {'real', 'finite', 'size', [nMeasurements, nState]});
validateattributes(noiseCovariance, {'numeric'}, ...
    {'real', 'finite', 'size', [nMeasurements, nMeasurements]});

barrierConfig = validateBarrierConfig(barrierConfig);
lambdaInc = barrierConfig.lambda_inc;
lambdaBox = barrierConfig.lambda_box;
interiorMargin = barrierConfig.interiorMargin;
covarianceMode = "gauss_newton";
if isfield(barrierConfig, 'covarianceMode')
    covarianceMode = string(barrierConfig.covarianceMode);
end
assert(isscalar(covarianceMode) && any(covarianceMode == ...
    ["gauss_newton", "exact_hessian"]), ...
    'dynsc:InvalidBarrierCovarianceMode', ...
    ['barrierConfig.covarianceMode must be "gauss_newton" or ' ...
     '"exact_hessian".']);

updateMethod = "barrier_virtual_measurement";
if isfield(barrierConfig, 'updateMethod')
    updateMethod = string(barrierConfig.updateMethod);
end

predictedCovariance = ...
    0.5 * (predictedCovariance + predictedCovariance');
noiseCovariance = 0.5 * (noiseCovariance + noiseCovariance');

[predictedFactor, predictedFlag] = chol( ...
    predictedCovariance, 'lower');
assert(predictedFlag == 0, ...
    'dynsc:NonPositiveDefinitePredictionCovariance', ...
    'The predicted covariance must be symmetric positive definite.');
[noiseFactor, noiseFlag] = chol(noiseCovariance, 'lower');
assert(noiseFlag == 0, ...
    'dynsc:NonPositiveDefiniteMeasurementCovariance', ...
    'The measurement-noise covariance must be symmetric positive definite.');

priorPrecision = predictedFactor' \ ...
    (predictedFactor \ eye(nState));
noisePrecision = noiseFactor' \ ...
    (noiseFactor \ eye(nMeasurements));
linearMeasurementInformation = H' * noisePrecision * H;
LambdaNormal = priorPrecision + linearMeasurementInformation;
LambdaNormal = 0.5 * (LambdaNormal + LambdaNormal');

inclusionSlackMatrix = ...
    dynsc.topology.buildInclusionSlackMatrix( ...
        topology.boundaryEdges, nEdges, nTriangles);
initialState = makeStrictlyFeasibleStart( ...
    predictedState, topology.boundaryEdges, nEdges, nTriangles, ...
    inclusionSlackMatrix, interiorMargin);

objective = @(state) barrierObjective( ...
    state, predictedState, priorPrecision, y, H, noisePrecision, ...
    inclusionSlackMatrix, lambdaInc, lambdaBox);
hessian = @(state, ~) barrierObjectiveHessian( ...
    state, LambdaNormal, inclusionSlackMatrix, lambdaInc, lambdaBox);

options = optimoptions('fmincon', ...
    'Algorithm', 'interior-point', ...
    'Display', 'none', ...
    'SpecifyObjectiveGradient', true, ...
    'HessianFcn', hessian, ...
    'MaxIterations', barrierConfig.maxIterations, ...
    'MaxFunctionEvaluations', barrierConfig.maxFunctionEvaluations, ...
    'OptimalityTolerance', barrierConfig.optimalityTolerance, ...
    'StepTolerance', barrierConfig.stepTolerance, ...
    'ConstraintTolerance', min(1e-10, interiorMargin / 10));

Aineq = -inclusionSlackMatrix;
bineq = -interiorMargin * ones(size(inclusionSlackMatrix, 1), 1);
lowerBound = interiorMargin * ones(nState, 1);
upperBound = (1 - interiorMargin) * ones(nState, 1);

[updatedState, objectiveValue, exitflag, solverOutput, multipliers] = ...
    fmincon(objective, initialState, Aineq, bineq, [], [], ...
        lowerBound, upperBound, [], options);
updatedState = updatedState(:);
assert(exitflag > 0, 'dynsc:BarrierUpdateFailed', ...
    'fmincon did not converge: %s', solverOutput.message);

barrierMeasurement = dynsc.update.barrierMeasurements( ...
    updatedState, inclusionSlackMatrix);
assert(all(barrierMeasurement.inclusionSlack > 0), ...
    'dynsc:NonPositiveInclusionSlack', ...
    'The corrected state has a nonpositive inclusion slack.');
assert(all(updatedState > 0 & updatedState < 1), ...
    'dynsc:StateOutsideOpenBox', ...
    'The corrected state must lie strictly inside the unit box.');

[inclusionCurvature, boxCurvature] = barrierCurvature( ...
    updatedState, inclusionSlackMatrix);

switch covarianceMode
    case "gauss_newton"
        inclusionInformation = 2 * lambdaInc * ...
            (barrierMeasurement.inclusionJacobian * ...
             barrierMeasurement.inclusionJacobian');
        boxInformation = 2 * lambdaBox * ...
            (barrierMeasurement.boxJacobian * ...
             barrierMeasurement.boxJacobian');

    case "exact_hessian"
        inclusionInformation = lambdaInc * inclusionCurvature;
        boxInformation = lambdaBox * boxCurvature;
end

inclusionInformation = 0.5 * ...
    (inclusionInformation + inclusionInformation');
boxInformation = 0.5 * (boxInformation + boxInformation');
informationMatrix = LambdaNormal + ...
    inclusionInformation + boxInformation;
informationMatrix = 0.5 * ...
    (informationMatrix + informationMatrix');

[informationFactor, informationFlag] = chol( ...
    informationMatrix, 'lower');
assert(informationFlag == 0, ...
    'dynsc:NonPositiveDefiniteInformationMatrix', ...
    'The barrier posterior information matrix must be positive definite.');
updatedCovariance = informationFactor' \ ...
    (informationFactor \ eye(nState));
updatedCovariance = 0.5 * ...
    (updatedCovariance + updatedCovariance');

symmetryScale = max(1, norm(updatedCovariance, 'fro'));
assert(norm(updatedCovariance - updatedCovariance', 'fro') <= ...
    1e-12 * symmetryScale, 'dynsc:AsymmetricPosteriorCovariance', ...
    'PPost must be numerically symmetric.');
minimumEigenvalue = min(eig(updatedCovariance));
psdTolerance = 1e-10 * max(1, norm(updatedCovariance, 2));
assert(minimumEigenvalue >= -psdTolerance, ...
    'dynsc:IndefinitePosteriorCovariance', ...
    'PPost must be numerically positive semidefinite.');

priorResidual = updatedState - predictedState;
measurementResidual = y - H * updatedState;
objectiveTerms = decomposeObjective( ...
    priorResidual, priorPrecision, measurementResidual, ...
    noiseCovariance, barrierMeasurement, lambdaInc, lambdaBox);
objectiveScale = max(1, abs(objectiveValue));
assert(abs(objectiveTerms.total - objectiveValue) <= ...
    1e-8 * objectiveScale, 'dynsc:BarrierObjectiveMismatch', ...
    'The reported barrier objective terms do not sum to the solver value.');

solverResult = struct();
solverResult.exitflag = exitflag;
solverResult.output = solverOutput;
solverResult.multipliers = multipliers;
solverResult.initialState = initialState;

update = struct();
update.method = updateMethod;
update.covarianceApproximation = covarianceMode;
update.solverName = "fmincon-interior-point";
update.solverStatus = "CONVERGED";
update.state = updatedState;
update.covariance = updatedCovariance;
update.priorResidual = priorResidual;
update.measurementResidual = measurementResidual;
update.objectiveValue = objectiveValue;
update.objectiveTerms = objectiveTerms;
update.priorPrecision = priorPrecision;
update.linearMeasurementInformation = linearMeasurementInformation;
update.LambdaNormal = LambdaNormal;
update.informationMatrix = informationMatrix;
update.informationTerms.inclusion = inclusionInformation;
update.informationTerms.box = boxInformation;
update.informationTerms.totalBarrier = ...
    inclusionInformation + boxInformation;
update.barrierMeasurement = barrierMeasurement;
update.inclusionSlackMatrix = inclusionSlackMatrix;
update.impliedNoiseVariance.inclusion = 1 / (2 * lambdaInc);
update.impliedNoiseVariance.box = 1 / (2 * lambdaBox);
update.minimumCovarianceEigenvalue = minimumEigenvalue;
update.solverResult = solverResult;
update.gurobiResult = [];
update.gurobiModel = [];
end

function cfg = validateBarrierConfig(cfg)
required = {
    'lambda_inc'
    'lambda_box'
    'interiorMargin'
    'maxIterations'
    'maxFunctionEvaluations'
    'optimalityTolerance'
    'stepTolerance'
};
for iField = 1:numel(required)
    assert(isfield(cfg, required{iField}), ...
        'dynsc:MissingBarrierUpdateConfig', ...
        'Missing cfg.update.barrier.%s.', required{iField});
end

validateattributes(cfg.lambda_inc, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(cfg.lambda_box, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(cfg.interiorMargin, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<', 1e-3});
validateattributes(cfg.maxIterations, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.maxFunctionEvaluations, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.optimalityTolerance, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(cfg.stepTolerance, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
end

function initialState = makeStrictlyFeasibleStart( ...
    predictedState, boundaryEdges, nEdges, nTriangles, ...
    inclusionSlackMatrix, interiorMargin)
candidate = min(max(predictedState, 0), 1);

for iTriangle = 1:nTriangles
    triangleIndex = nEdges + iTriangle;
    minimumBoundaryValue = min(candidate(boundaryEdges(iTriangle, :)));
    candidate(triangleIndex) = min( ...
        candidate(triangleIndex), minimumBoundaryValue);
end

% Convexly mix with a fixed strictly feasible SC. This preserves the
% candidate's shape while guaranteeing room for every logarithm.
reference = [
    0.75 * ones(nEdges, 1)
    0.25 * ones(nTriangles, 1)
];
initialState = 0.9 * candidate + 0.1 * reference;

assert(all(initialState > interiorMargin & ...
    initialState < 1 - interiorMargin), ...
    'dynsc:NoStrictlyFeasibleBarrierStart', ...
    'Could not construct a strictly interior box-constrained start.');
assert(all(inclusionSlackMatrix * initialState > interiorMargin), ...
    'dynsc:NoStrictlyFeasibleBarrierStart', ...
    'Could not construct strictly positive inclusion slacks.');
end

function [value, gradient] = barrierObjective( ...
    state, predictedState, priorPrecision, y, H, noisePrecision, ...
    inclusionSlackMatrix, lambdaInc, lambdaBox)
priorResidual = state - predictedState;
measurementResidual = y - H * state;
inclusionSlack = inclusionSlackMatrix * state;

if any(inclusionSlack <= 0) || any(state <= 0 | state >= 1)
    value = Inf;
    gradient = zeros(size(state));
    return;
end

inclusionBarrier = -sum(log(inclusionSlack));
boxBarrier = -sum(log(state) + log1p(-state));
value = 0.5 * priorResidual' * priorPrecision * priorResidual + ...
    0.5 * measurementResidual' * noisePrecision * ...
        measurementResidual + ...
    lambdaInc * inclusionBarrier + lambdaBox * boxBarrier;

gradient = priorPrecision * priorResidual - ...
    H' * noisePrecision * measurementResidual - ...
    lambdaInc * inclusionSlackMatrix' * (1 ./ inclusionSlack) + ...
    lambdaBox * (-1 ./ state + 1 ./ (1 - state));
end

function hessian = barrierObjectiveHessian( ...
    state, LambdaNormal, inclusionSlackMatrix, lambdaInc, lambdaBox)
inclusionSlack = inclusionSlackMatrix * state;
assert(all(inclusionSlack > 0) && all(state > 0 & state < 1), ...
    'dynsc:BarrierHessianOutsideDomain', ...
    'The barrier Hessian is defined only in the strict feasible interior.');

[inclusionCurvature, boxCurvature] = barrierCurvature( ...
    state, inclusionSlackMatrix);
hessian = LambdaNormal + ...
    lambdaInc * inclusionCurvature + lambdaBox * boxCurvature;
hessian = 0.5 * (hessian + hessian');
end

function [inclusionCurvature, boxCurvature] = barrierCurvature( ...
    state, inclusionSlackMatrix)
inclusionSlack = inclusionSlackMatrix * state;
assert(all(inclusionSlack > 0) && all(state > 0 & state < 1), ...
    'dynsc:BarrierHessianOutsideDomain', ...
    'The barrier Hessian is defined only in the strict feasible interior.');

nInclusions = numel(inclusionSlack);
inclusionCurvature = inclusionSlackMatrix' * ...
    spdiags(1 ./ inclusionSlack.^2, 0, nInclusions, nInclusions) * ...
    inclusionSlackMatrix;
boxCurvature = spdiags( ...
    1 ./ state.^2 + 1 ./ (1 - state).^2, ...
    0, numel(state), numel(state));
end

function terms = decomposeObjective( ...
    priorResidual, priorPrecision, measurementResidual, ...
    noiseCovariance, barrierMeasurement, lambdaInc, lambdaBox)
offDiagonalNoise = noiseCovariance - diag(diag(noiseCovariance));
noiseScale = max(1, norm(noiseCovariance, 'fro'));
assert(norm(offDiagonalNoise, 'fro') <= 1e-12 * noiseScale, ...
    'dynsc:NonDiagonalMeasurementCovariance', ...
    ['The objective decomposition requires independent linear virtual-' ...
     'measurement errors.']);

measurementVariances = diag(noiseCovariance);
terms = struct();
terms.prior = 0.5 * ...
    (priorResidual' * priorPrecision * priorResidual);
terms.smoothness = 0.5 * ...
    measurementResidual(1)^2 / measurementVariances(1);
terms.edgeTotal = 0.5 * ...
    measurementResidual(2)^2 / measurementVariances(2);
terms.triangleTotal = 0.5 * ...
    measurementResidual(3)^2 / measurementVariances(3);
terms.measurementTotal = terms.smoothness + ...
    terms.edgeTotal + terms.triangleTotal;
terms.normalTotal = terms.prior + terms.measurementTotal;
terms.inclusionBarrierUnscaled = ...
    barrierMeasurement.inclusionBarrier;
terms.boxBarrierUnscaled = barrierMeasurement.boxBarrier;
terms.inclusionBarrier = lambdaInc * ...
    terms.inclusionBarrierUnscaled;
terms.boxBarrier = lambdaBox * terms.boxBarrierUnscaled;
terms.barrierTotal = terms.inclusionBarrier + terms.boxBarrier;
terms.total = terms.normalTotal + terms.barrierTotal;
end
