function cfg = validateConfig(cfg)
%VALIDATECONFIG Fail early when a generation configuration is incomplete.

% Older experiment configurations retain the historical Gurobi correction.
if ~isfield(cfg, 'update') || isempty(cfg.update)
    cfg.update.method = "constrained_map";
elseif ~isfield(cfg.update, 'method')
    cfg.update.method = "constrained_map";
end

requiredFields = [
    "experiment.name"
    "experiment.seed"
    "experiment.numRealizations"
    "topology.generator"
    "topology.numNodes"
    "topology.edgeProbability"
    "topology.triangleFraction"
    "topology.changeInterval"
    "signals.generator"
    "signals.numTimeSteps"
    "signals.numNodeSignals"
    "signals.numEdgeSignals"
    "signals.smoothnessType"
    "signals.sigma"
    "signals.normalizeNoise"
    "signals.verbose"
    "prediction.F"
    "prediction.Q"
    "prediction.skipFirstPrediction"
    "prediction.initialState"
    "prediction.initialCovariance"
    "measurement.builder"
    "measurement.smoothnessType"
    "measurement.C1"
    "measurement.C2"
    "measurement.noiseVariances"
    "metrics.evaluator"
    "metrics.supportThreshold"
    "baseline.solver"
    "output.root"
    "output.saveRealizations"
];

for iField = 1:numel(requiredFields)
    assert(hasNestedField(cfg, requiredFields(iField)), ...
        'dynsc:MissingConfig', ...
        'Missing configuration field: cfg.%s', requiredFields(iField));
end

assert(isa(cfg.topology.generator, 'function_handle'), ...
    'dynsc:InvalidTopologyGenerator', ...
    'cfg.topology.generator must be a function handle.');
assert(isa(cfg.signals.generator, 'function_handle'), ...
    'dynsc:InvalidSignalGenerator', ...
    'cfg.signals.generator must be a function handle.');
assert(isa(cfg.measurement.builder, 'function_handle'), ...
    'dynsc:InvalidMeasurementBuilder', ...
    'cfg.measurement.builder must be a function handle.');
assert(isa(cfg.metrics.evaluator, 'function_handle'), ...
    'dynsc:InvalidMetricsEvaluator', ...
    'cfg.metrics.evaluator must be a function handle.');
assert(isa(cfg.baseline.solver, 'function_handle'), ...
    'dynsc:InvalidBaselineSolver', ...
    'cfg.baseline.solver must be a function handle.');
skipFirstPrediction = cfg.prediction.skipFirstPrediction;
assert(isscalar(skipFirstPrediction) && ...
    (islogical(skipFirstPrediction) || ...
    (isnumeric(skipFirstPrediction) && isreal(skipFirstPrediction) && ...
    isfinite(skipFirstPrediction) && ...
    any(skipFirstPrediction == [0, 1]))), ...
    'dynsc:InvalidSkipFirstPrediction', ...
    ['cfg.prediction.skipFirstPrediction must be a scalar logical ' ...
     'value.']);
cfg.prediction.skipFirstPrediction = logical(skipFirstPrediction);
if isfield(cfg.baseline, 'static')
    assert(isfield(cfg.baseline.static, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Static-baseline configuration requires ' ...
         'cfg.baseline.static.enabled.']);
    staticEnabled = cfg.baseline.static.enabled;
    assert(isscalar(staticEnabled) && ...
        (islogical(staticEnabled) || ...
        (isnumeric(staticEnabled) && isreal(staticEnabled) && ...
        isfinite(staticEnabled) && any(staticEnabled == [0, 1]))), ...
        'dynsc:InvalidStaticBaselineSetting', ...
        ['cfg.baseline.static.enabled must be a scalar logical ' ...
         'value.']);
    cfg.baseline.static.enabled = logical(staticEnabled);
end
if isfield(cfg.baseline, 'identityTransition')
    assert(isfield(cfg.baseline.identityTransition, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Persistence-prior baseline configuration requires ' ...
         'cfg.baseline.identityTransition.enabled.']);
    identityEnabled = cfg.baseline.identityTransition.enabled;
    assert(isscalar(identityEnabled) && ...
        (islogical(identityEnabled) || ...
        (isnumeric(identityEnabled) && isreal(identityEnabled) && ...
        isfinite(identityEnabled) && any(identityEnabled == [0, 1]))), ...
        'dynsc:InvalidIdentityBaselineSetting', ...
        ['cfg.baseline.identityTransition.enabled must be a scalar ' ...
         'logical value.']);
    cfg.baseline.identityTransition.enabled = ...
        logical(cfg.baseline.identityTransition.enabled);
end
if isfield(cfg.baseline, 'constrainedRls')
    assert(isfield(cfg.baseline.constrainedRls, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Constrained-RLS baseline configuration requires ' ...
         'cfg.baseline.constrainedRls.enabled.']);
    constrainedRlsEnabled = cfg.baseline.constrainedRls.enabled;
    assert(isscalar(constrainedRlsEnabled) && ...
        (islogical(constrainedRlsEnabled) || ...
        (isnumeric(constrainedRlsEnabled) && ...
        isreal(constrainedRlsEnabled) && ...
        isfinite(constrainedRlsEnabled) && ...
        any(constrainedRlsEnabled == [0, 1]))), ...
        'dynsc:InvalidConstrainedRlsBaselineSetting', ...
        ['cfg.baseline.constrainedRls.enabled must be a scalar logical ' ...
         'value.']);
    cfg.baseline.constrainedRls.enabled = ...
        logical(constrainedRlsEnabled);
end
if isfield(cfg.baseline, 'previousUpdate')
    assert(isfield(cfg.baseline.previousUpdate, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Previous-update baseline configuration requires ' ...
         'cfg.baseline.previousUpdate.enabled.']);
    previousUpdateEnabled = cfg.baseline.previousUpdate.enabled;
    assert(isscalar(previousUpdateEnabled) && ...
        (islogical(previousUpdateEnabled) || ...
        (isnumeric(previousUpdateEnabled) && ...
        isreal(previousUpdateEnabled) && ...
        isfinite(previousUpdateEnabled) && ...
        any(previousUpdateEnabled == [0, 1]))), ...
        'dynsc:InvalidPreviousUpdateBaselineSetting', ...
        ['cfg.baseline.previousUpdate.enabled must be a scalar ' ...
         'logical value.']);
    cfg.baseline.previousUpdate.enabled = ...
        logical(cfg.baseline.previousUpdate.enabled);
end
if isfield(cfg.baseline, 'exactHessianUpdate')
    assert(isfield(cfg.baseline.exactHessianUpdate, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Exact-Hessian baseline configuration requires ' ...
         'cfg.baseline.exactHessianUpdate.enabled.']);
    exactHessianEnabled = cfg.baseline.exactHessianUpdate.enabled;
    assert(isscalar(exactHessianEnabled) && ...
        (islogical(exactHessianEnabled) || ...
        (isnumeric(exactHessianEnabled) && ...
        isreal(exactHessianEnabled) && ...
        isfinite(exactHessianEnabled) && ...
        any(exactHessianEnabled == [0, 1]))), ...
        'dynsc:InvalidExactHessianBaselineSetting', ...
        ['cfg.baseline.exactHessianUpdate.enabled must be a scalar ' ...
         'logical value.']);
    cfg.baseline.exactHessianUpdate.enabled = ...
        logical(cfg.baseline.exactHessianUpdate.enabled);
end
if isfield(cfg.baseline, 'standardEkfBarrier')
    assert(isfield(cfg.baseline.standardEkfBarrier, 'enabled'), ...
        'dynsc:MissingConfig', ...
        ['Standard-EKF barrier baseline configuration requires ' ...
         'cfg.baseline.standardEkfBarrier.enabled.']);
    standardEkfEnabled = cfg.baseline.standardEkfBarrier.enabled;
    assert(isscalar(standardEkfEnabled) && ...
        (islogical(standardEkfEnabled) || ...
        (isnumeric(standardEkfEnabled) && ...
        isreal(standardEkfEnabled) && ...
        isfinite(standardEkfEnabled) && ...
        any(standardEkfEnabled == [0, 1]))), ...
        'dynsc:InvalidStandardEkfBaselineSetting', ...
        ['cfg.baseline.standardEkfBarrier.enabled must be a scalar ' ...
         'logical value.']);
    cfg.baseline.standardEkfBarrier.enabled = ...
        logical(cfg.baseline.standardEkfBarrier.enabled);
end

validateattributes(cfg.experiment.seed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative', 'finite'});
validateattributes(cfg.experiment.numRealizations, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.topology.numNodes, {'numeric'}, ...
    {'scalar', 'integer', '>=', 3, 'finite'});
validateattributes(cfg.topology.edgeProbability, {'numeric'}, ...
    {'scalar', '>', 0, '<=', 1, 'finite'});
validateattributes(cfg.topology.triangleFraction, {'numeric'}, ...
    {'scalar', '>=', 0, '<=', 1, 'finite'});
validateattributes(cfg.topology.changeInterval, {'numeric'}, ...
    {'scalar', 'integer', '>=', 2, 'finite'});
validateattributes(cfg.signals.numTimeSteps, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.signals.numNodeSignals, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.signals.numEdgeSignals, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(cfg.signals.sigma, {'numeric'}, ...
    {'scalar', 'nonnegative', 'finite'});

smoothnessType = string(cfg.signals.smoothnessType);
validTypes = ["low_curl", "smooth", "new_smoothness"];
assert(isscalar(smoothnessType) && any(smoothnessType == validTypes), ...
    'dynsc:InvalidSmoothnessType', ...
    ['cfg.signals.smoothnessType must be "low_curl" or ' ...
     '"new_smoothness".']);
if smoothnessType == "smooth"
    smoothnessType = "low_curl";
end
cfg.signals.smoothnessType = smoothnessType;

expectedEdgeCount = nchoosek(cfg.topology.numNodes, 2);
expectedTriangleCount = nchoosek(cfg.topology.numNodes, 3);
expectedStateSize = expectedEdgeCount + expectedTriangleCount;
usesClosureAwareGenerator = strcmp( ...
    func2str(cfg.topology.generator), ...
    func2str(@dynsc.topology.generateClosureAwareMarkov));
usesClosureAwarePrediction = ...
    dynsc.prediction.predictionModel(cfg.prediction) == "closure_aware";

transitionNames = {'beta1', 'rho1', 'beta2', 'rho2'};
if usesClosureAwareGenerator
    assert(isfield(cfg, 'transition'), ...
        'dynsc:MissingTransitionParameters', ...
        'Closure-aware generation requires cfg.transition.');
    for iParameter = 1:numel(transitionNames)
        parameterName = transitionNames{iParameter};
        assert(isfield(cfg.transition, parameterName), ...
            'dynsc:MissingTransitionParameter', ...
            'Missing cfg.transition.%s.', parameterName);
        validateattributes(cfg.transition.(parameterName), {'numeric'}, ...
            {'scalar', 'real', 'finite', '>=', 0, '<=', 1});
    end
    cfg.topology.transition = cfg.transition;
end
if usesClosureAwarePrediction
    % Older configurations used cfg.transition for both generation and
    % prediction. Retain that behavior only when no estimator-side values
    % were supplied explicitly.
    if ~isfield(cfg.prediction, 'transition') || ...
            isempty(cfg.prediction.transition)
        assert(isfield(cfg, 'transition'), ...
            'dynsc:MissingTransitionParameters', ...
            ['Closure-aware prediction requires ' ...
             'cfg.prediction.transition.']);
        cfg.prediction.transition = cfg.transition;
    end
    for iParameter = 1:numel(transitionNames)
        parameterName = transitionNames{iParameter};
        assert(isfield(cfg.prediction.transition, parameterName), ...
            'dynsc:MissingTransitionParameter', ...
            'Missing cfg.prediction.transition.%s.', parameterName);
        validateattributes( ...
            cfg.prediction.transition.(parameterName), {'numeric'}, ...
            {'scalar', 'real', 'finite', '>=', 0, '<=', 1});
    end
end
if ~isempty(cfg.prediction.Q)
    cfg.prediction = dynsc.prediction.resolveProcessNoise( ...
        cfg.prediction, expectedEdgeCount, expectedTriangleCount);
end

if dynsc.prediction.isConfigured(cfg.prediction)
    cfg.prediction = dynsc.prediction.validateParameters( ...
        cfg.prediction, expectedStateSize);

    if isfield(cfg.prediction, 'initialization') && ...
            isfield(cfg.prediction.initialization, 'method') && ...
            any(string(cfg.prediction.initialization.method) == ...
                ["bernoulli", "ground_truth"])
        assert(isfield(cfg.prediction.initialization, 'varianceFloor'), ...
            'dynsc:MissingConfig', ...
            ['Bernoulli and ground-truth initialization require ' ...
             'cfg.prediction.initialization.varianceFloor.']);
        validateattributes( ...
            cfg.prediction.initialization.varianceFloor, {'numeric'}, ...
            {'scalar', 'real', 'finite', 'positive'});
    end
end

measurementSmoothnessType = string(cfg.measurement.smoothnessType);
validMeasurementTypes = ["low_curl", "new", "new_smoothness"];
assert(isscalar(measurementSmoothnessType) && ...
    any(measurementSmoothnessType == validMeasurementTypes), ...
    'dynsc:InvalidMeasurementSmoothnessType', ...
    ['cfg.measurement.smoothnessType must be "low_curl" or ' ...
     '"new_smoothness".']);
if measurementSmoothnessType == "new"
    measurementSmoothnessType = "new_smoothness";
end
cfg.measurement.smoothnessType = measurementSmoothnessType;

if dynsc.measurement.isConfigured(cfg.measurement)
    validateattributes(cfg.measurement.noiseVariances, {'numeric'}, ...
        {'real', 'finite', 'nonnegative', 'numel', 3});
    cfg.measurement.noiseVariances = ...
        cfg.measurement.noiseVariances(:);
end

updateMethod = string(cfg.update.method);
validUpdateMethods = ["constrained_map", ...
    "barrier_virtual_measurement", "barrier_exact_hessian", ...
    "barrier_standard_ekf_projection"];
assert(isscalar(updateMethod) && any(updateMethod == validUpdateMethods), ...
    'dynsc:InvalidUpdateMethod', ...
    ['cfg.update.method must be "constrained_map", ' ...
     '"barrier_virtual_measurement", "barrier_exact_hessian", or ' ...
     '"barrier_standard_ekf_projection".']);
cfg.update.method = updateMethod;

standardEkfBaselineEnabled = isfield(cfg.baseline, ...
    'standardEkfBarrier') && ...
    logical(cfg.baseline.standardEkfBarrier.enabled);
if any(updateMethod == ...
        ["barrier_virtual_measurement", "barrier_exact_hessian", ...
         "barrier_standard_ekf_projection"]) || ...
        standardEkfBaselineEnabled
    assert(isfield(cfg.update, 'barrier'), ...
        'dynsc:MissingBarrierUpdateConfig', ...
        ['The selected log-barrier update requires ' ...
         'cfg.update.barrier.']);
    requiredBarrierFields = {
        'lambda_inc'
        'lambda_box'
        'interiorMargin'
        'maxIterations'
        'maxFunctionEvaluations'
        'optimalityTolerance'
        'stepTolerance'
    };
    for iField = 1:numel(requiredBarrierFields)
        fieldName = requiredBarrierFields{iField};
        assert(isfield(cfg.update.barrier, fieldName), ...
            'dynsc:MissingBarrierUpdateConfig', ...
            'Missing cfg.update.barrier.%s.', fieldName);
    end
    validateattributes(cfg.update.barrier.lambda_inc, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(cfg.update.barrier.lambda_box, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(cfg.update.barrier.interiorMargin, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive', '<', 1e-3});
    validateattributes(cfg.update.barrier.maxIterations, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'});
    validateattributes( ...
        cfg.update.barrier.maxFunctionEvaluations, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'});
    validateattributes( ...
        cfg.update.barrier.optimalityTolerance, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(cfg.update.barrier.stepTolerance, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
end

validateattributes(cfg.metrics.supportThreshold, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', 1});

if isfield(cfg, 'plot') && isfield(cfg.plot, 'stateSnapshots')
    assert(isfield(cfg.plot.stateSnapshots, 'enabled') && ...
        isfield(cfg.plot.stateSnapshots, 'interval'), ...
        'dynsc:IncompleteStateSnapshotConfiguration', ...
        ['State-snapshot plotting requires both enabled and interval ' ...
         'settings.']);
    validateattributes(cfg.plot.stateSnapshots.enabled, ...
        {'logical', 'numeric'}, {'scalar'});
    cfg.plot.stateSnapshots.enabled = ...
        logical(cfg.plot.stateSnapshots.enabled);
    validateattributes(cfg.plot.stateSnapshots.interval, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'});
end

if isfield(cfg, 'plot') && isfield(cfg.plot, 'average')
    assert(isfield(cfg.plot.average, 'showStandardDeviation'), ...
        'dynsc:IncompleteAveragePlotConfiguration', ...
        ['Average-plot configuration requires the ' ...
         'showStandardDeviation setting.']);
    validateattributes(cfg.plot.average.showStandardDeviation, ...
        {'logical', 'numeric'}, {'scalar'});
    cfg.plot.average.showStandardDeviation = ...
        logical(cfg.plot.average.showStandardDeviation);
end

cfg.output.root = char(cfg.output.root);
end

function tf = hasNestedField(value, fieldPath)
parts = split(fieldPath, ".");
tf = true;

for iPart = 1:numel(parts)
    part = char(parts(iPart));
    if ~isstruct(value) || ~isfield(value, part)
        tf = false;
        return;
    end
    value = value.(part);
end
end
