function [nodeMap, rawContacts] = buildPrimarySchoolNodeMap( ...
    officialContactsFile, metadataFile)
%BUILDPRIMARYSCHOOLNODEMAP Recover AHORN IDs and attach class metadata.
%
% The ScHoLP conversion labels nodes 1,...,242 in order of first appearance
% in the official pairwise contact stream. This function reconstructs that
% deterministic relabeling and joins the official class/gender metadata.

assert(isfile(officialContactsFile), 'dynsc:MissingOfficialContacts', ...
    'Official contact file not found: %s', officialContactsFile);
assert(isfile(metadataFile), 'dynsc:MissingPrimarySchoolMetadata', ...
    'Primary-school metadata file not found: %s', metadataFile);

temporaryFolder = tempname;
mkdir(temporaryFolder);
cleanup = onCleanup(@() removeTemporaryFolder(temporaryFolder));
unzippedFiles = gunzip(officialContactsFile, temporaryFolder);
assert(isscalar(unzippedFiles), 'dynsc:UnexpectedContactArchive', ...
    'Expected the official archive to contain exactly one file.');

contactFileId = fopen(unzippedFiles{1}, 'r');
assert(contactFileId >= 0, 'dynsc:CannotOpenOfficialContacts', ...
    'Could not open official contact data.');
contactCleanup = onCleanup(@() fclose(contactFileId));
contactColumns = textscan(contactFileId, '%f%f%f%s%s', ...
    'Delimiter', '\t', 'MultipleDelimsAsOne', true);

rawContacts = table( ...
    contactColumns{1}, contactColumns{2}, contactColumns{3}, ...
    string(contactColumns{4}), string(contactColumns{5}), ...
    'VariableNames', { ...
        'TimeSeconds', 'OriginalId1', 'OriginalId2', ...
        'Class1', 'Class2'});

metadataFileId = fopen(metadataFile, 'r');
assert(metadataFileId >= 0, 'dynsc:CannotOpenMetadata', ...
    'Could not open primary-school metadata.');
metadataCleanup = onCleanup(@() fclose(metadataFileId));
metadataColumns = textscan(metadataFileId, '%f%s%s', ...
    'Delimiter', '\t', 'MultipleDelimsAsOne', true);
metadata = table( ...
    metadataColumns{1}, string(metadataColumns{2}), ...
    string(metadataColumns{3}), ...
    'VariableNames', {'OriginalId', 'Class', 'Gender'});

appearanceOrder = reshape( ...
    [rawContacts.OriginalId1, rawContacts.OriginalId2].', [], 1);
originalIds = unique(appearanceOrder, 'stable');
[foundMetadata, metadataLocation] = ismember( ...
    originalIds, metadata.OriginalId);
assert(all(foundMetadata), 'dynsc:MissingNodeMetadata', ...
    'At least one contact participant is absent from the metadata file.');

nNodes = numel(originalIds);
nodeMap = table( ...
    (1:nNodes).', originalIds, ...
    metadata.Class(metadataLocation), metadata.Gender(metadataLocation), ...
    'VariableNames', {'AhornId', 'OriginalId', 'Class', 'Gender'});

assert(nNodes == 242, 'dynsc:UnexpectedPrimarySchoolNodeCount', ...
    'Expected 242 mapped participants, found %d.', nNodes);

clear contactCleanup metadataCleanup cleanup
end

function removeTemporaryFolder(folder)
if isfolder(folder)
    rmdir(folder, 's');
end
end
