function [predictedState, predictedCovariance, F] = ...
    predictClosureAwareState( ...
        previousState, previousCovariance, boundaryEdges, parameters, Q)
%PREDICTCLOSUREAWARESTATE Perform one nonlinear EKF prediction.

previousState = previousState(:);
nState = numel(previousState);
validateattributes(previousCovariance, {'numeric'}, ...
    {'real', 'finite', 'size', [nState, nState]});
validateattributes(Q, {'numeric'}, ...
    {'real', 'finite', 'size', [nState, nState]});

predictedState = dynsc.prediction.closureAwareTransition( ...
    previousState, boundaryEdges, parameters);
F = dynsc.prediction.closureAwareJacobian( ...
    previousState, boundaryEdges, parameters);
predictedCovariance = F * previousCovariance * F' + Q;
predictedCovariance = full( ...
    0.5 * (predictedCovariance + predictedCovariance'));
end
