function [Q, details] = processNoiseAtState( ...
    cfg, state, boundaryEdges)
%PROCESSNOISEATSTATE Resolve the process covariance for one prediction.

state = state(:);
details = struct();

if isnumeric(cfg.Q)
    Q = cfg.Q;
    details.specification = "manual";
    return;
end

specification = string(cfg.Q);
assert(isscalar(specification), ...
    'dynsc:InvalidProcessNoiseSpecification', ...
    'The process-noise specification must be scalar text.');

nTriangles = size(boundaryEdges, 1);
nEdges = numel(state) - nTriangles;
assert(nEdges > 0, 'dynsc:InvalidClosureAwareStateSize', ...
    'The state must contain an edge block followed by a triangle block.');

switch specification
    case "bernoulli_second_moment"
        assert(isfield(cfg, 'transition'), ...
            'dynsc:MissingTransitionParameters', ...
            ['Bernoulli process noise requires ' ...
             'cfg.prediction.transition.']);
        [Q, details] = ...
            dynsc.prediction.bernoulliTransitionCovariance( ...
                state, boundaryEdges, cfg.transition);
        details.specification = specification;

    case "block_diagonal"
        assert(isfield(cfg, 'processNoise') && ...
            isfield(cfg.processNoise, 'qEdge') && ...
            isfield(cfg.processNoise, 'qTriangle'), ...
            'dynsc:MissingProcessNoiseParameters', ...
            ['Block-diagonal process noise requires processNoise.qEdge ' ...
             'and processNoise.qTriangle.']);
        qEdge = cfg.processNoise.qEdge;
        qTriangle = cfg.processNoise.qTriangle;
        validateattributes(qEdge, {'numeric'}, ...
            {'scalar', 'real', 'finite', 'nonnegative'});
        validateattributes(qTriangle, {'numeric'}, ...
            {'scalar', 'real', 'finite', 'nonnegative'});
        Q = blkdiag(qEdge * speye(nEdges), ...
            qTriangle * speye(nTriangles));
        details.specification = specification;

    otherwise
        error('dynsc:InvalidProcessNoiseSpecification', ...
            ['Text-valued Q must be "block_diagonal" or ' ...
             '"bernoulli_second_moment".']);
end
end
