function cfg = validateParameters(cfg, expectedStateSize)
%VALIDATEPARAMETERS Check dimensions and covariance validity.

if ~isfield(cfg, 'skipFirstPrediction')
    % Preserve the historical behavior for direct callers with old configs.
    cfg.skipFirstPrediction = false;
end
skipFirstPrediction = cfg.skipFirstPrediction;
assert(isscalar(skipFirstPrediction) && ...
    (islogical(skipFirstPrediction) || ...
    (isnumeric(skipFirstPrediction) && isreal(skipFirstPrediction) && ...
    isfinite(skipFirstPrediction) && ...
    any(skipFirstPrediction == [0, 1]))), ...
    'dynsc:InvalidSkipFirstPrediction', ...
    'skipFirstPrediction must be a scalar logical value.');
cfg.skipFirstPrediction = logical(skipFirstPrediction);

initializationProvided = [
    ~isempty(cfg.initialState)
    ~isempty(cfg.initialCovariance)
];
assert(~any(initializationProvided) || all(initializationProvided), ...
    'dynsc:IncompletePredictionInitialization', ...
    ['initialState and initialCovariance must either both be supplied or ' ...
     'both be empty.']);

if nargin < 2
    assert(all(initializationProvided), ...
        'dynsc:UnresolvedPredictionInitialization', ...
        ['Resolve the prediction initialization before validating the ' ...
         'complete prediction model.']);
    cfg.initialState = cfg.initialState(:);
    nState = numel(cfg.initialState);
else
    validateattributes(expectedStateSize, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'});
    nState = expectedStateSize;
    if all(initializationProvided)
        cfg.initialState = cfg.initialState(:);
        assert(numel(cfg.initialState) == nState, ...
            'dynsc:StateSizeMismatch', ...
            'initialState must contain %d entries.', nState);
    end
end

usesBernoulliProcessNoise = false;
if isstring(cfg.Q) || ischar(cfg.Q)
    processNoiseSpecification = string(cfg.Q);
    validSpecifications = ...
        ["block_diagonal", "bernoulli_second_moment"];
    assert(isscalar(processNoiseSpecification) && ...
        any(processNoiseSpecification == validSpecifications), ...
        'dynsc:InvalidProcessNoiseSpecification', ...
        ['Text-valued Q must be "block_diagonal" or ' ...
         '"bernoulli_second_moment".']);
    cfg.Q = processNoiseSpecification;
    usesBernoulliProcessNoise = ...
        processNoiseSpecification == "bernoulli_second_moment";
else
    validateattributes(cfg.Q, {'numeric'}, ...
        {'real', 'finite', 'size', [nState, nState]});
    assertSymmetricPositiveSemidefinite(cfg.Q, 'Q');
end

model = dynsc.prediction.predictionModel(cfg);
if model == "linear"
    validateattributes(cfg.F, {'numeric'}, ...
        {'real', 'finite', 'size', [nState, nState]});
end

if model == "closure_aware" || usesBernoulliProcessNoise
    assert(isfield(cfg, 'transition'), ...
        'dynsc:MissingTransitionParameters', ...
        ['Closure-aware prediction and Bernoulli process noise require ' ...
         'cfg.prediction.transition.']);
end

if all(initializationProvided)
    validateattributes(cfg.initialCovariance, {'numeric'}, ...
        {'real', 'finite', 'size', [nState, nState]});
    assertSymmetricPositiveSemidefinite( ...
        cfg.initialCovariance, 'initialCovariance');
end
end

function assertSymmetricPositiveSemidefinite(matrix, name)
scale = max(1, norm(matrix, 'fro'));
tolerance = 1e-10 * scale;

assert(norm(matrix - matrix', 'fro') <= tolerance, ...
    'dynsc:NonSymmetricCovariance', ...
    '%s must be symmetric.', name);

minimumEigenvalue = min(eig((matrix + matrix') / 2));
assert(minimumEigenvalue >= -tolerance, ...
    'dynsc:NonPositiveSemidefiniteCovariance', ...
    '%s must be positive semidefinite.', name);
end
